// Native Flutter catalogue seed transcribed from the immutable founder-approved
// Buy V2 screenbook. Each row is one canonical product followed by its Shop and
// Wholesale offer facts. The production UI never reads or renders HTML.
const buyV2CommerceSeedRows = '''
tomato|Fresh tomatoes|Farm fresh|fruits-vegetables|fruits-vegetables|Red ripe · Grade A|500 g pack|37|₹74/kg|Lowest delivered price|Shree Balaji Fresh|Verified retailer|12 minutes|Quality refund within 24 hours|10 kg crate|580|₹58/kg|Best landed cost|Jodhpur Fresh Supply|Verified wholesaler|Tomorrow by 10:30 am|Shortage or quality claim within 12 hours
atta|Stone-ground wheat atta|Daily staples|flour-rice-grains|flour-rice-grains|Whole wheat · stone-ground|5 kg bag|279|₹55.80/kg|Best value|Sardarpura Supermart|Verified retailer|Today by 7:30 pm|Sealed pack · 7-day return|Case of 10 × 5 kg|2420|₹48.40/kg|Lowest delivered price|Marwar Foods Distribution|Verified distributor|Tomorrow by 2:00 pm|Sealed case return within three days
oil|Refined sunflower oil|Kitchen essentials|oils-ghee|oils-ghee|Refined sunflower · food-grade|5 L can|835|₹167/L|Lowest delivered price|Ghar Bazaar|Verified retailer|Today by 8:00 pm|Replacement for damaged seal|Case of 4 × 5 L|3096|₹154.80/L|Manufacturer offer|Surya Oils India|Verified manufacturer|Dispatch in one day|Transit damage replacement
rice|Premium basmati rice|Daily staples|flour-rice-grains|flour-rice-grains|Aged basmati · premium grain|5 kg bag|395|₹79/kg|Popular nearby|Rajasthan Mart|Verified retailer|25 minutes|Sealed pack · 7-day return|25 kg bag|1690|₹67.60/kg|Best landed cost|Thar Grains Wholesale|Verified wholesaler|Tomorrow by 5:00 pm|Sealed bag return within three days
soap|Herbal bathing soap|Personal care|bath-hand-care|bath-hand-care|Herbal · family care|Pack of 4|164|₹41 each|Best value|Ghar Bazaar|Verified retailer|30 minutes|Unopened pack · 7-day return|Case of 48|1680|₹35 each|Lowest delivered price|Care Products Distribution|Verified distributor|Within two days|Sealed case return within three days
notebook|A4 ruled notebooks|Home and school|school-office|stationery-office|A4 · ruled pages|Pack of 6|210|₹35 each|Popular nearby|Family Stationery|Verified shop|Today by 6:30 pm|Unused pack · 7-day return|Carton of 120|3480|₹29 each|Best landed cost|Rajasthan Paper Products|Verified manufacturer|Within three days|Transit damage replacement
onion|Fresh red onions|Farm fresh|fruits-vegetables|fruits-vegetables|Vegetable · sealed pack|1 kg pack|42|₹42/kg|Lowest delivered price|Jodhpur Fresh Mart|Verified retailer|18 minutes|Eligibility and return window shown before payment|25 kg sack|775|₹31/kg|Best landed cost|Marwar Fresh Supply|Verified producer group|Dispatch within one day|Transit or quality claim within the stated inspection window
milk|Toned fresh milk|Daily dairy|dairy-bakery|dairy-bakery|Doodh · quality checked|1 L pouch|66|₹66/L|Best value|Family Dairy & Bake|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Crate of 12 × 1 L|660|₹55/L|Trade price|Rajasthan Chilled Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
bread|Whole wheat bread|Fresh bakery|dairy-bakery|dairy-bakery|Bakery · quality checked|400 g loaf|45|₹112.50/kg|Popular nearby|Family Dairy & Bake|Verified retailer|18 minutes|Eligibility and return window shown before payment|Tray of 24 loaves|720|₹30/loaf|Best landed cost|Rajasthan Chilled Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
eggs|Farm fresh eggs|Protein foods|eggs-poultry|eggs-poultry|Anda · sealed pack|6 eggs|89|₹14.83/egg|Lowest delivered price|Safe Protein Store|Verified retailer|Today by 7:30 pm|Replacement or refund within 24 hours for damaged, spoiled or incorrect packs; no return after opening|Tray lot of 180 eggs|1600|₹8.89/egg|Trade price|Marwar Cold Chain Foods|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
chicken|Fresh chicken curry cut|Cold-chain fresh|eggs-poultry|eggs-poultry|Poultry · sealed pack|1 kg pack|285|₹285/kg|Best value|Safe Protein Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|10 kg foodservice pack|2400|₹240/kg|Best landed cost|Marwar Cold Chain Foods|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
ghee|Pure cow ghee|Kitchen essentials|oils-ghee|oils-ghee|Clarified butter · sealed pack|1 L jar|625|₹625/L|Popular nearby|Ghar Bazaar|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 10 × 1 L|5700|₹570/L|Trade price|Surya Oils India|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
turmeric|Turmeric powder|Everyday spices|ground-spices|ground-spices|Haldi · sealed pack|200 g pack|78|₹390/kg|Lowest delivered price|Masala Ghar|Verified retailer|18 minutes|Eligibility and return window shown before payment|10 kg trade pack|3100|₹310/kg|Best landed cost|Marwar Spice Works|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
cumin|Whole cumin seeds|Everyday spices|whole-spices|whole-spices|Jeera · sealed pack|200 g pack|95|₹475/kg|Best value|Masala Ghar|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|10 kg trade pack|3900|₹390/kg|Trade price|Marwar Spice Works|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
poha|Thick breakfast poha|Morning staples|breakfast-cereals|breakfast-cereals|Flattened rice · sealed pack|1 kg pack|72|₹72/kg|Popular nearby|Morning Supply|Verified retailer|18 minutes|Eligibility and return window shown before payment|25 kg sack|1250|₹50/kg|Best landed cost|Rajasthan Foods Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
oats|Wholegrain rolled oats|Morning staples|breakfast-cereals|breakfast-cereals|Breakfast · sealed pack|1 kg pack|195|₹195/kg|Lowest delivered price|Morning Supply|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 12 × 1 kg|1980|₹165/kg|Trade price|Rajasthan Foods Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
noodles|Instant masala noodles|Quick meals|instant-foods|instant-foods|Instant · sealed pack|Pack of 6|84|₹14/pack|Best value|Family Supermart|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 120 packs|1080|₹9/pack|Best landed cost|Jodhpur Packaged Foods Hub|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
pasta|Durum wheat pasta|Quick meals|instant-foods|instant-foods|Macaroni · sealed pack|1 kg pack|110|₹110/kg|Popular nearby|Family Supermart|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|25 kg foodservice pack|2250|₹90/kg|Trade price|Jodhpur Packaged Foods Hub|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
biscuits|Glucose biscuits|Tea-time favourites|biscuits-chocolate|biscuits-chocolate|Cookies · sealed pack|Pack of 6|60|₹10/pack|Lowest delivered price|Snack Street|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 240 packs|1650|₹6.88/pack|Best landed cost|Marwar Snacks Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
namkeen|Classic bhujia namkeen|Tea-time favourites|namkeen-chips|namkeen-chips|Bhujia · sealed pack|400 g pack|85|₹212.50/kg|Best value|Snack Street|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 30 × 400 g|1680|₹140/kg|Trade price|Marwar Snacks Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
tea|Strong leaf tea|Daily beverages|tea-coffee|tea-coffee|Chai · sealed pack|500 g pack|265|₹530/kg|Popular nearby|Daily Drinks Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|10 kg trade pack|4150|₹415/kg|Best landed cost|Rajasthan Beverage Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
juice|Mixed fruit juice|Daily beverages|juices-water|juices-water|Fruit drink · sealed pack|1 L carton|110|₹110/L|Lowest delivered price|Daily Drinks Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 × 1 L|2100|₹87.50/L|Trade price|Rajasthan Beverage Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
peas|Frozen green peas|Frozen fresh|frozen-foods|frozen-foods|Matar · sealed pack|1 kg pack|155|₹155/kg|Best value|Fresh & Frozen|Verified retailer|18 minutes|Eligibility and return window shown before payment|20 kg cold-chain case|2800|₹140/kg|Best landed cost|Jodhpur Cold Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
ice-cream|Vanilla ice cream|Frozen favourites|icecream-cheese|icecream-cheese|Dessert · sealed pack|1 L tub|220|₹220/L|Popular nearby|Fresh & Frozen|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 12 × 1 L|2400|₹200/L|Trade price|Jodhpur Cold Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
toothpaste|Family fluoride toothpaste|Personal care|oral-care|oral-care|Oral care · sealed pack|Pack of 2|190|₹95/tube|Lowest delivered price|Care Corner|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 tubes|1680|₹70/tube|Best landed cost|Marwar Care Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
shampoo|Daily care shampoo|Beauty & grooming|hair-care|hair-care|Hair care · sealed pack|650 ml bottle|299|₹460/L|Best value|Beauty Supply|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 20 bottles|4800|₹240/bottle|Trade price|Rajasthan Beauty Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
face-wash|Gentle face wash|Beauty & grooming|skin-care|skin-care|Skin care · sealed pack|100 ml tube|179|₹1.79/ml|Popular nearby|Beauty Supply|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 tubes|3200|₹133.33/tube|Best landed cost|Rajasthan Beauty Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
floor-cleaner|Disinfectant floor cleaner|Home care|surface-cleaners|surface-cleaners|Disinfectant · sealed pack|2 L bottle|210|₹105/L|Lowest delivered price|Home Essentials|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|20 L institutional can|2800|₹140/L|Trade price|Jodhpur Home Care Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
toilet-cleaner|Power toilet cleaner|Home care|surface-cleaners|surface-cleaners|Bathroom · sealed pack|2 L bottle|195|₹97.50/L|Best value|Home Essentials|Verified retailer|18 minutes|Eligibility and return window shown before payment|20 L institutional can|2500|₹125/L|Best landed cost|Jodhpur Home Care Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
detergent|Front-load detergent powder|Laundry care|laundry-dishwash|laundry-dishwash|Washing powder · sealed pack|5 kg pack|590|₹118/kg|Popular nearby|Clean Home Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|25 kg trade pack|2200|₹88/kg|Trade price|Marwar Cleaning Products|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
dishwash|Lemon dishwash bars|Cleaning essentials|laundry-dishwash|laundry-dishwash|Utensil cleaner · sealed pack|Pack of 4|95|₹23.75/bar|Lowest delivered price|Clean Home Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 96 bars|1600|₹16.67/bar|Best landed cost|Marwar Cleaning Products|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
diapers|Baby diapers medium|Baby care|diapers-wipes|diapers-wipes|Baby nappy · sealed pack|42 diapers|699|₹16.64/diaper|Best value|Baby Needs|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 8 packs|5600|₹700/pack|Trade price|Rajasthan Baby Care Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
baby-wipes|Unscented baby wipes|Baby care|diapers-wipes|diapers-wipes|Baby hygiene · sealed pack|72 wipes|180|₹2.50/wipe|Popular nearby|Baby Needs|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 18 packs|2400|₹133.33/pack|Best landed cost|Rajasthan Baby Care Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
chyawanprash|Herbal chyawanprash|Daily wellness|health-wellness|health-wellness|Immunity · sealed pack|1 kg jar|360|₹360/kg|Lowest delivered price|Wellness Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 12 × 1 kg|3400|₹283.33/kg|Trade price|Marwar Wellness Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
protein|Everyday nutrition protein|Daily wellness|health-wellness|health-wellness|Nutrition · sealed pack|1 kg jar|899|₹899/kg|Best value|Wellness Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 10 × 1 kg|7800|₹780/kg|Best landed cost|Marwar Wellness Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
dog-food|Adult dog food|Pet nutrition|dog-care|dog-care|Pet food · sealed pack|3 kg bag|699|₹233/kg|Popular nearby|Pet Family Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|25 kg breeder pack|4850|₹194/kg|Trade price|Rajasthan Pet Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
cat-food|Adult cat food|Pet nutrition|cat-care|cat-care|Pet food · sealed pack|3 kg bag|620|₹206.67/kg|Lowest delivered price|Pet Family Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|25 kg breeder pack|4400|₹176/kg|Best landed cost|Rajasthan Pet Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
foil|Food-grade aluminium foil|Kitchen essentials|food-storage-packs|horeca-food-packs|Food wrap · sealed pack|25 m roll|110|₹4.40/m|Best value|Kitchen Needs|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 30 rolls|2100|₹70/roll|Trade price|Marwar Foodservice Supply|Verified wholesaler|Delivery within two days|Transit or quality claim within the stated inspection window
paper-cups|Food-safe paper cups|Kitchen essentials|cups-tissues|horeca-tableware|Disposable · sealed pack|Pack of 50|125|₹2.50/cup|Popular nearby|Kitchen Needs|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 1,000 cups|1600|₹1.60/cup|Best landed cost|Marwar Foodservice Supply|Verified wholesaler|Dispatch within one day|Transit or quality claim within the stated inspection window
thermal-rolls|POS thermal paper rolls|Store essentials|shop-supplies|retail-supplies|BPA-free · retail POS|10 rolls|170|₹17/roll|Lowest delivered price|Family Stationery|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 200 rolls|2100|₹10.50/roll|Trade price|Rajasthan Retail Supply|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
price-labels|Self-adhesive price labels|Store essentials|shop-supplies|retail-supplies|Retail label · sealed pack|10 rolls|145|₹14.50/roll|Best value|Family Stationery|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 200 rolls|1750|₹8.75/roll|Best landed cost|Rajasthan Retail Supply|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
pencils|HB graphite pencils|Home and school|school-office|stationery-office|School · sealed pack|20 pencils|120|₹6/pencil|Popular nearby|Family Stationery|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 500 pencils|1900|₹3.80/pencil|Trade price|Rajasthan Paper Products|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
banana|Fresh bananas|Farm fresh|fruits-vegetables|fruits-vegetables|Naturally ripened · Grade A|1 kg pack|58|₹58/kg|Lowest delivered price|Jodhpur Fresh Mart|Verified retailer|18 minutes|Eligibility and return window shown before payment|20 kg crate|820|₹41/kg|Best landed cost|Marwar Fresh Supply|Verified producer group|Dispatch within one day|Transit or quality claim within the stated inspection window
potato|Fresh potatoes|Farm fresh|fruits-vegetables|fruits-vegetables|Fresh table potato · Grade A|2 kg pack|68|₹34/kg|Best value|Jodhpur Fresh Mart|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|25 kg sack|625|₹25/kg|Trade price|Marwar Fresh Supply|Verified producer group|Delivery within two days|Transit or quality claim within the stated inspection window
curd|Fresh set curd|Daily dairy|dairy-bakery|dairy-bakery|Plain set curd · chilled|400 g tub|48|₹120/kg|Popular nearby|Family Dairy & Bake|Verified retailer|18 minutes|Eligibility and return window shown before payment|Crate of 24 × 400 g|936|₹97.50/kg|Best landed cost|Rajasthan Chilled Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
paneer|Fresh malai paneer|Daily dairy|dairy-bakery|dairy-bakery|Malai paneer · chilled|200 g pack|92|₹460/kg|Lowest delivered price|Family Dairy & Bake|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|10 kg foodservice pack|3650|₹365/kg|Trade price|Rajasthan Chilled Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
fish-fillet|Fresh boneless fish fillets|Cold-chain fresh|meat-seafood|meat-seafood|Boneless fillet · chilled|500 g pack|310|₹620/kg|Best value|Safe Protein Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|10 kg foodservice pack|5150|₹515/kg|Best landed cost|Marwar Cold Chain Foods|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
mutton|Fresh mutton curry cut|Cold-chain fresh|meat-seafood|meat-seafood|Curry cut · chilled|500 g pack|465|₹930/kg|Popular nearby|Safe Protein Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|10 kg foodservice pack|7900|₹790/kg|Trade price|Marwar Cold Chain Foods|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
toor-dal|Unpolished toor dal|Daily staples|dals-staples|dals-staples|Unpolished · premium grain|1 kg pack|168|₹168/kg|Lowest delivered price|Rajasthan Mart|Verified retailer|18 minutes|Eligibility and return window shown before payment|30 kg sack|4200|₹140/kg|Best landed cost|Thar Grains Wholesale|Verified wholesaler|Dispatch within one day|Transit or quality claim within the stated inspection window
sugar|Fine crystal sugar|Daily staples|dals-staples|dals-staples|Chini · sealed pack|2 kg pack|104|₹52/kg|Best value|Rajasthan Mart|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|50 kg sack|2200|₹44/kg|Trade price|Thar Grains Wholesale|Verified wholesaler|Delivery within two days|Transit or quality claim within the stated inspection window
mustard-oil|Cold-pressed mustard oil|Kitchen essentials|oils-ghee|oils-ghee|Cold-pressed · filtered|1 L bottle|188|₹188/L|Popular nearby|Ghar Bazaar|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 15 × 1 L|2460|₹164/L|Best landed cost|Surya Oils India|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
groundnut-oil|Filtered groundnut oil|Kitchen essentials|oils-ghee|oils-ghee|Filtered · food-grade|1 L bottle|210|₹210/L|Lowest delivered price|Ghar Bazaar|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 15 × 1 L|2790|₹186/L|Trade price|Surya Oils India|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
red-chilli|Red chilli powder|Everyday spices|ground-spices|ground-spices|Fine ground · pure spice|200 g pack|82|₹410/kg|Best value|Masala Ghar|Verified retailer|18 minutes|Eligibility and return window shown before payment|10 kg trade pack|3300|₹330/kg|Best landed cost|Marwar Spice Works|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
coriander-seeds|Whole coriander seeds|Everyday spices|whole-spices|whole-spices|Whole seed · cleaned|200 g pack|64|₹320/kg|Popular nearby|Masala Ghar|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|10 kg trade pack|2450|₹245/kg|Trade price|Marwar Spice Works|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
corn-flakes|Crunchy corn flakes|Morning staples|breakfast-cereals|breakfast-cereals|Breakfast cereal · sealed pack|750 g pack|215|₹286.67/kg|Lowest delivered price|Morning Supply|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 12 × 750 g|2160|₹240/kg|Best landed cost|Rajasthan Foods Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
idli-mix|Ready idli batter mix|Morning staples|instant-foods|instant-foods|Instant breakfast · sealed pack|1 kg pack|145|₹145/kg|Best value|Morning Supply|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 20 × 1 kg|2380|₹119/kg|Trade price|Rajasthan Foods Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
ketchup|Classic tomato ketchup|Meal companions|sauces-spreads|sauces-spreads|Tomato sauce · sealed pack|950 g pouch|135|₹142.11/kg|Popular nearby|Family Supermart|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 × 950 g|2640|₹115.79/kg|Best landed cost|Jodhpur Packaged Foods Hub|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
jam|Mixed fruit jam|Meal companions|sauces-spreads|sauces-spreads|Fruit spread · sealed pack|500 g jar|165|₹330/kg|Lowest delivered price|Family Supermart|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 × 500 g|3240|₹270/kg|Trade price|Jodhpur Packaged Foods Hub|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
potato-chips|Salted potato chips|Tea-time favourites|namkeen-chips|namkeen-chips|Crisps · sealed pack|Pack of 6|120|₹20/pack|Best value|Snack Street|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 120 packs|1680|₹14/pack|Best landed cost|Marwar Snacks Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
chocolate|Milk chocolate bars|Sweet favourites|biscuits-chocolate|biscuits-chocolate|Candy · sealed pack|Pack of 6|210|₹35/bar|Popular nearby|Snack Street|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 144 bars|3960|₹27.50/bar|Trade price|Marwar Snacks Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
coffee|Instant coffee|Daily beverages|tea-coffee|tea-coffee|Hot drink · sealed pack|200 g jar|395|₹1,975/kg|Lowest delivered price|Daily Drinks Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 × 200 g|7920|₹1,650/kg|Best landed cost|Rajasthan Beverage Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
water|Packaged drinking water|Daily beverages|juices-water|juices-water|Mineral water · sealed pack|Pack of 12 × 1 L|180|₹15/L|Best value|Daily Drinks Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Pallet of 60 packs|8100|₹11.25/L|Trade price|Rajasthan Beverage Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
frozen-fries|Frozen potato fries|Frozen favourites|frozen-foods|frozen-foods|French fries · sealed pack|1 kg pack|225|₹225/kg|Popular nearby|Fresh & Frozen|Verified retailer|18 minutes|Eligibility and return window shown before payment|20 kg foodservice case|3800|₹190/kg|Best landed cost|Jodhpur Cold Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
cheese-slices|Processed cheese slices|Chilled favourites|icecream-cheese|icecream-cheese|Cheese · sealed pack|400 g pack|285|₹712.50/kg|Lowest delivered price|Fresh & Frozen|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 20 × 400 g|4700|₹587.50/kg|Trade price|Jodhpur Cold Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
toothbrush|Soft family toothbrushes|Personal care|oral-care|oral-care|Oral care · sealed pack|Pack of 4|140|₹35/brush|Best value|Care Corner|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 96 brushes|2400|₹25/brush|Best landed cost|Marwar Care Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
handwash|Gentle liquid handwash|Personal care|bath-hand-care|bath-hand-care|Hand care · sealed pack|750 ml refill|135|₹180/L|Popular nearby|Care Corner|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 refills|2520|₹140/L|Trade price|Marwar Care Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
moisturizer|Daily skin moisturizer|Beauty & grooming|skin-care|skin-care|Skin care · sealed pack|200 ml bottle|245|₹1.23/ml|Lowest delivered price|Beauty Supply|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 bottles|4680|₹195/bottle|Best landed cost|Rajasthan Beauty Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
hair-oil|Nourishing coconut hair oil|Beauty & grooming|hair-care|hair-care|Hair care · sealed pack|500 ml bottle|195|₹390/L|Best value|Beauty Supply|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 bottles|3720|₹155/bottle|Trade price|Rajasthan Beauty Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
garbage-bags|Strong garbage bags|Home essentials|air-waste-care|air-waste-care|Waste bags · sealed pack|Pack of 30|145|₹4.83/bag|Popular nearby|Home Essentials|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 1,200 bags|3960|₹3.30/bag|Best landed cost|Jodhpur Home Care Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
air-freshener|Long-lasting air freshener|Home essentials|air-waste-care|air-waste-care|Room freshener · sealed pack|240 ml can|185|₹0.77/ml|Lowest delivered price|Home Essentials|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 cans|3480|₹145/can|Trade price|Jodhpur Home Care Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
fabric-conditioner|Fresh fabric conditioner|Laundry care|laundry-dishwash|laundry-dishwash|Fabric softener · sealed pack|2 L bottle|320|₹160/L|Best value|Clean Home Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 12 × 2 L|3120|₹130/L|Best landed cost|Marwar Cleaning Products|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
liquid-detergent|Liquid laundry detergent|Laundry care|laundry-dishwash|laundry-dishwash|Washing liquid · sealed pack|2 L bottle|295|₹147.50/L|Popular nearby|Clean Home Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|20 L institutional can|2360|₹118/L|Trade price|Marwar Cleaning Products|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
baby-lotion|Gentle baby lotion|Baby care|baby-care|baby-care|Baby skin · sealed pack|400 ml bottle|285|₹0.71/ml|Lowest delivered price|Baby Needs|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 bottles|5400|₹225/bottle|Best landed cost|Rajasthan Baby Care Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
baby-cereal|Rice and milk baby cereal|Baby nutrition|baby-care|baby-care|Infant food · sealed pack|300 g pack|245|₹816.67/kg|Best value|Baby Needs|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 packs|4680|₹650/kg|Trade price|Rajasthan Baby Care Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
glucose|Instant energy glucose|Daily wellness|health-wellness|health-wellness|Energy drink · sealed pack|1 kg pack|165|₹165/kg|Popular nearby|Wellness Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 20 × 1 kg|2700|₹135/kg|Best landed cost|Marwar Wellness Distribution|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
sanitary-pads|Ultra-soft sanitary pads|Daily wellness|health-wellness|health-wellness|Period care · sealed pack|Pack of 30|285|₹9.50/pad|Lowest delivered price|Wellness Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Case of 24 packs|5640|₹7.83/pad|Trade price|Marwar Wellness Distribution|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
dog-treats|Chicken dog treats|Pet nutrition|dog-care|dog-care|Dog snack · sealed pack|500 g pack|245|₹490/kg|Best value|Pet Family Store|Verified retailer|18 minutes|Eligibility and return window shown before payment|Case of 24 packs|4680|₹390/kg|Best landed cost|Rajasthan Pet Supply|Verified distributor|Dispatch within one day|Transit or quality claim within the stated inspection window
cat-litter|Clumping cat litter|Pet hygiene|cat-care|cat-care|Cat hygiene · sealed pack|5 kg bag|425|₹85/kg|Popular nearby|Pet Family Store|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|25 kg breeder pack|1750|₹70/kg|Trade price|Rajasthan Pet Supply|Verified distributor|Delivery within two days|Transit or quality claim within the stated inspection window
tissues|Food-safe paper tissues|Kitchen essentials|cups-tissues|horeca-tableware|Napkin · sealed pack|Pack of 200|85|₹0.43/tissue|Lowest delivered price|Kitchen Needs|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 8,000 tissues|2320|₹0.29/tissue|Best landed cost|Marwar Foodservice Supply|Verified wholesaler|Dispatch within one day|Transit or quality claim within the stated inspection window
takeaway-containers|Food-safe takeaway containers|Kitchen essentials|food-storage-packs|horeca-food-packs|Food box · sealed pack|Pack of 25|175|₹7/container|Best value|Kitchen Needs|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 1,000|4300|₹4.30/container|Trade price|Marwar Foodservice Supply|Verified wholesaler|Delivery within two days|Transit or quality claim within the stated inspection window
barcode-labels|Barcode label rolls|Store essentials|shop-supplies|retail-supplies|Self-adhesive · retail grade|10 rolls|260|₹26/roll|Popular nearby|Family Stationery|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 200 rolls|3600|₹18/roll|Best landed cost|Rajasthan Retail Supply|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
carry-bags|Reusable retail carry bags|Store essentials|food-storage-packs|retail-supplies|Reusable · reinforced handle|Pack of 25|220|₹8.80/bag|Lowest delivered price|Kitchen Needs|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 1,000 bags|5400|₹5.40/bag|Trade price|Rajasthan Retail Supply|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
printer-paper|A4 copier paper|Office essentials|school-office|stationery-office|A4 · 75 GSM|Ream of 500 sheets|295|₹0.59/sheet|Best value|Family Stationery|Verified retailer|18 minutes|Eligibility and return window shown before payment|Carton of 10 reams|2460|₹246/ream|Best landed cost|Rajasthan Paper Products|Verified manufacturer|Dispatch within one day|Transit or quality claim within the stated inspection window
ball-pens|Smooth blue ball pens|Office essentials|school-office|stationery-office|Blue ink · smooth tip|Pack of 20|140|₹7/pen|Popular nearby|Family Stationery|Verified retailer|Today by 7:30 pm|Eligibility and return window shown before payment|Carton of 1,000 pens|4200|₹4.20/pen|Trade price|Rajasthan Paper Products|Verified manufacturer|Delivery within two days|Transit or quality claim within the stated inspection window
''';
