import type { AdminCase, AdminScreen } from "./admin-types";

const fact = (label: string, value: string) => ({ label, value });
const step = (label: string, outcome: string) => ({ label, outcome });

const commonConfirmation =
  "I reviewed the evidence, affected users, permitted scope and recorded reason.";

const adminCase = (
  value: Omit<AdminCase, "confirmation"> & { confirmation?: string },
): AdminCase => ({
  ...value,
  confirmation: value.confirmation ?? commonConfirmation,
});

export const adminScreens: AdminScreen[] = [
  {
    screen: 147,
    navLabel: "Command",
    path: "/admin",
    title: "Operations Command Centre",
    subtitle: "Platform health, priority exceptions and accountable ownership",
    role: "Incident Commander",
    stats: [
      { label: "PLATFORM HEALTH", value: "99.96%", note: "Core journeys available" },
      { label: "CRITICAL", value: "3", note: "Owned and within target" },
      { label: "USERS LIVE", value: "1.84L", note: "People and workspaces" },
      { label: "MONEY FLOW", value: "₹2.8Cr", note: "99.7% matched today" },
    ],
    filters: ["Priority", "Commerce", "Ride", "Work", "Social", "Finance"],
    queueTitle: "Act now",
    queueNote: "Risk first, then customer impact",
    note: "Every exception has one owner, response target, reason and protected activity history.",
    items: [
      adminCase({
        id: "payment-safety",
        kicker: "P1 · PAYMENT SAFETY",
        title: "UPI callback delay affecting 184 payments",
        meta: "Finance Operations · started 8 minutes ago",
        status: "Critical",
        tone: "critical",
        time: "07:12 left",
        facts: [
          fact("CUSTOMERS", "184"),
          fact("VALUE", "₹3.42L"),
          fact("OWNER", "Finance Ops"),
          fact("FALLBACK", "Active"),
        ],
        detail:
          "Payments remain pending rather than failed. Duplicate payment is blocked and customers see the current status.",
        steps: [
          step("Contain", "Retry and duplicate guards active"),
          step("Reconcile", "Payment-provider events matched to money records"),
          step("Resolve", "Release one final payment state"),
          step("Notify", "Affected customers receive the result"),
        ],
        currentStep: 1,
        primary: "Open finance incident",
        secondary: "Acknowledge",
        primaryOutcome:
          "Finance incident opened with the current payment evidence.",
        secondaryOutcome:
          "Incident acknowledged. Ownership and response target remain unchanged.",
        tags: ["Priority", "Commerce", "Finance"],
      }),
      adminCase({
        id: "ride-safety",
        kicker: "P1 · RIDE SAFETY",
        title: "Captain SOS escalation in Jodhpur",
        meta: "Ride RD-90218 · customer and captain connected",
        status: "Critical",
        tone: "critical",
        time: "02:48 left",
        facts: [
          fact("RIDE", "RD-90218"),
          fact("LOCATION", "Jodhpur"),
          fact("CONTACT", "Connected"),
          fact("TEAM", "Safety"),
        ],
        detail:
          "The safety team owns this incident. Location is limited to authorized responders and retained under policy.",
        steps: [
          step("Connect", "Safety call established"),
          step("Assess", "Incident facts and permitted location"),
          step("Assist", "Emergency protocol when required"),
          step("Close", "Reason, evidence and welfare check"),
        ],
        currentStep: 1,
        primary: "Open safety incident",
        secondary: "Acknowledge",
        primaryOutcome:
          "Safety incident opened for the authorized response team.",
        secondaryOutcome:
          "Safety alert acknowledged without exposing location to other teams.",
        tags: ["Priority", "Ride"],
        confirmation:
          "I am authorized for this safety purpose and reviewed the restricted-access notice.",
      }),
      adminCase({
        id: "order-capacity",
        kicker: "P2 · ORDER CAPACITY",
        title: "Retailer acceptance falling in Zone 4",
        meta: "42 customer orders need safe rerouting",
        status: "At risk",
        tone: "warning",
        time: "18:20 left",
        facts: [
          fact("ORDERS", "42"),
          fact("AREA", "Zone 4"),
          fact("STOCK FIT", "36"),
          fact("BACKUP", "8 shops"),
        ],
        detail:
          "Only shops with confirmed stock, readiness and acceptance reliability may receive rerouted demand.",
        steps: [
          step("Confirm stock", "Refresh eligible shops"),
          step("Reserve", "Hold matching quantity"),
          step("Reroute", "Offer under original customer terms"),
          step("Inform", "Update delivery time and provider"),
        ],
        currentStep: 0,
        primary: "Start safe reroute",
        secondary: "Acknowledge",
        primaryOutcome:
          "Eligible stock and original customer terms are ready for rerouting.",
        secondaryOutcome:
          "Capacity risk acknowledged and kept with the current owner.",
        tags: ["Priority", "Commerce"],
      }),
    ],
  },
  {
    screen: 148,
    navLabel: "Verification",
    path: "/admin/verification",
    title: "Workspace Verification",
    subtitle: "Exact profile proof and capability-level activation",
    role: "Verification Specialist",
    stats: [
      { label: "NEW CASES", value: "286", note: "Today" },
      { label: "DUE IN 2H", value: "34", note: "Priority review" },
      { label: "AUTO VERIFIED", value: "68%", note: "Trusted source match" },
      { label: "NEEDS USER", value: "41", note: "One clear action" },
    ],
    filters: ["Due now", "Retail", "Manufacturer", "Captain", "Provider", "Professional"],
    queueTitle: "Verification queue",
    queueNote: "Oldest valid case first",
    note: "Approve only capabilities supported by verified evidence. Personal access never depends on workspace approval.",
    items: [
      adminCase({
        id: "grocery-retailer",
        kicker: "GROCERY RETAILER · WP-256619",
        title: "Mahadev Fresh Mart",
        meta: "Jodhpur · identity verified · GST pending",
        status: "Review",
        tone: "warning",
        time: "23 min",
        facts: [
          fact("PROFILE", "Retailer"),
          fact("IDENTITY", "Verified"),
          fact("PREMISES", "Matched"),
          fact("GST", "Reminder due"),
        ],
        detail:
          "The shop may prepare its catalogue while tax-dependent capabilities stay unavailable until required evidence is verified.",
        steps: [
          step("Identity", "Owner and contact matched"),
          step("Business proof", "Premises and activity checked"),
          step("Capability access", "Retail functions resolved"),
          step("Decision", "Activate with exact limits"),
        ],
        currentStep: 2,
        primary: "Approve permitted access",
        secondary: "Request one item",
        primaryOutcome:
          "Only evidence-backed retailer capabilities were approved.",
        secondaryOutcome:
          "One precise GST action was sent; verified evidence remains saved.",
        tags: ["Due now", "Retail"],
      }),
      adminCase({
        id: "doctor",
        kicker: "INDIVIDUAL DOCTOR · WP-256702",
        title: "Dr. Meera Sharma",
        meta: "Rajasthan Medical Council record matched",
        status: "Specialist",
        tone: "warning",
        time: "41 min",
        facts: [
          fact("PROFILE", "Doctor"),
          fact("REGISTRATION", "Matched"),
          fact("PRACTICE", "Jodhpur"),
          fact("PAYOUT", "Name matched"),
        ],
        detail:
          "A clinical verification specialist confirms registration, consultation modes and expiry monitoring before patient visibility.",
        steps: [
          step("Identity", "Doctor identity verified"),
          step("Professional record", "Council record matched"),
          step("Practice readiness", "Location and modes"),
          step("Clinical approval", "Specialist decision"),
        ],
        currentStep: 3,
        primary: "Record specialist decision",
        primaryOutcome:
          "Specialist decision recorded with exact clinical capability limits.",
        tags: ["Due now", "Professional", "Provider"],
        confirmation:
          "I am the assigned clinical specialist and reviewed registration, permitted modes and expiry.",
      }),
      adminCase({
        id: "restaurant",
        kicker: "RESTAURANT · WP-256744",
        title: "Spice Route Restaurant",
        meta: "Food licence matched · premises image unclear",
        status: "User action",
        tone: "warning",
        time: "1 h",
        facts: [
          fact("PROFILE", "Restaurant"),
          fact("FOOD LICENCE", "Matched"),
          fact("PREMISES", "Unclear"),
          fact("OWNER", "Verified"),
        ],
        detail:
          "Ask only for the missing premises image. Existing verified data remains saved.",
        steps: [
          step("Identity", "Complete"),
          step("Food licence", "Complete"),
          step("Premises", "One clearer image"),
          step("Activation", "Waiting"),
        ],
        currentStep: 2,
        primary: "Send precise request",
        primaryOutcome:
          "A request for one clearer premises image was sent.",
        tags: ["Due now", "Provider"],
      }),
    ],
  },
  {
    screen: 149,
    navLabel: "Catalogue",
    path: "/admin/catalogue",
    title: "Catalogue and SKU Governance",
    subtitle: "Canonical products, provider offers and customer decision quality",
    role: "Catalogue Controller",
    stats: [
      { label: "MASTER SKUs", value: "48,620", note: "Versioned" },
      { label: "PENDING MATCH", value: "318", note: "Supplier submissions" },
      { label: "DUPLICATES", value: "46", note: "High confidence" },
      { label: "BLOCKED", value: "19", note: "Safety or proof" },
    ],
    filters: ["Needs match", "Duplicate", "Price anomaly", "Regulated", "Missing proof"],
    queueTitle: "Governance queue",
    queueNote: "Customer decision quality first",
    note: "The canonical product stays separate from supplier offers and retailer live stock.",
    items: [
      adminCase({
        id: "sunflower-oil",
        kicker: "SKU MATCH · 98.7%",
        title: "Fortune Sunflower Oil 1 L",
        meta: "Manufacturer GTIN matches canonical pack",
        status: "Confirm",
        tone: "neutral",
        time: "12 min",
        facts: [
          fact("GTIN", "8906007280012"),
          fact("BRAND", "Fortune"),
          fact("PACK", "1 L"),
          fact("SOURCE", "Manufacturer"),
        ],
        detail:
          "Confirm product identity while supplier quantity, wholesale price, delivery and payment terms remain separate offers.",
        steps: [
          step("Identity", "GTIN and brand match"),
          step("Attributes", "Pack and category normalized"),
          step("Offer separation", "Commercial terms stay supplier-owned"),
          step("Publish", "Available to eligible catalogues"),
        ],
        currentStep: 2,
        primary: "Confirm canonical SKU",
        primaryOutcome:
          "Canonical SKU confirmed without changing supplier offers.",
        tags: ["Needs match"],
      }),
      adminCase({
        id: "atta-duplicate",
        kicker: "DUPLICATE CANDIDATE",
        title: "Aashirvaad Whole Wheat Atta 5 kg",
        meta: "Two local spellings point to the same GTIN",
        status: "Merge",
        tone: "warning",
        time: "18 min",
        facts: [
          fact("RECORDS", "2"),
          fact("GTIN", "Same"),
          fact("STOCK LINKS", "1,284"),
          fact("RISK", "Low"),
        ],
        detail:
          "Merge aliases without changing shop stock, supplier orders or historical invoices.",
        steps: [
          step("Compare", "Identity and pack"),
          step("Impact", "Linked stock and orders"),
          step("Merge", "Canonical alias update"),
          step("Refresh", "Search results update"),
        ],
        currentStep: 1,
        primary: "Approve safe merge",
        primaryOutcome:
          "Aliases merged while stock, orders and invoices stayed unchanged.",
        tags: ["Duplicate"],
      }),
      adminCase({
        id: "medicine",
        kicker: "REGULATED PRODUCT",
        title: "Prescription medicine submission",
        meta: "Pharmacy licence valid · medicine source incomplete",
        status: "Blocked",
        tone: "critical",
        time: "29 min",
        facts: [
          fact("LICENCE", "Valid"),
          fact("BATCH", "Present"),
          fact("SOURCE", "Missing"),
          fact("VISIBILITY", "Off"),
        ],
        detail:
          "Customer visibility stays off until source and required medicine data pass the licensed workflow.",
        steps: [
          step("Licence", "Verified"),
          step("Medicine data", "Parsed"),
          step("Source proof", "Missing"),
          step("Publish", "Blocked"),
        ],
        currentStep: 2,
        primary: "Request source proof",
        secondary: "Keep blocked",
        primaryOutcome:
          "The pharmacy received one precise source-proof request.",
        secondaryOutcome:
          "Customer visibility remains safely blocked with the reason recorded.",
        tags: ["Regulated", "Missing proof"],
      }),
    ],
  },
  {
    screen: 150,
    navLabel: "Commerce",
    path: "/admin/commerce",
    title: "Commerce Operations",
    subtitle: "Orders, stock reservations, fulfilment and customer exceptions",
    role: "Commerce Controller",
    stats: [
      { label: "LIVE ORDERS", value: "8,420", note: "All fulfilment modes" },
      { label: "AT RISK", value: "62", note: "Needs action" },
      { label: "REROUTED", value: "94%", note: "Within original terms" },
      { label: "REFUND TARGET", value: "99.2%", note: "On time" },
    ],
    filters: ["At risk", "Stock mismatch", "Late", "Reroute", "Refund"],
    queueTitle: "Order exceptions",
    queueNote: "Customer promise first",
    note: "Every resolution uses a protected command. Operators cannot directly edit money or order records.",
    items: [
      adminCase({
        id: "stock-mismatch",
        kicker: "STOCK MISMATCH · OR-84291",
        title: "Shop cannot fulfil 2 of 6 items",
        meta: "Customer paid · home delivery · 3 backup shops",
        status: "Resolve",
        tone: "critical",
        time: "06:40 left",
        facts: [
          fact("ORDER", "₹645"),
          fact("MISSING", "2 items"),
          fact("BACKUP", "3 eligible"),
          fact("TIME IMPACT", "+8 min"),
        ],
        detail:
          "Preserve price and refund terms. Ask the customer only when substitution or split fulfilment changes the accepted decision.",
        steps: [
          step("Confirm", "Shop mismatch recorded"),
          step("Match", "Stock and reliability checked"),
          step("Customer choice", "Apply saved preference"),
          step("Fulfil", "Reroute or refund"),
        ],
        currentStep: 1,
        primary: "Apply best resolution",
        primaryOutcome:
          "The best eligible resolution is ready under the accepted customer terms.",
        tags: ["At risk", "Stock mismatch", "Reroute"],
      }),
      adminCase({
        id: "delivery-delay",
        kicker: "DELIVERY DELAY · OR-84308",
        title: "Delivery partner stopped moving for 9 minutes",
        meta: "Customer sees revised time · shop handover verified",
        status: "Monitor",
        tone: "warning",
        time: "11:22 left",
        facts: [
          fact("ORDER", "₹1,240"),
          fact("PARTNER", "DP-182"),
          fact("LOCATION", "Consented"),
          fact("TIME IMPACT", "+12 min"),
        ],
        detail:
          "Contact the partner, then reassign only if movement or response does not recover within the agreed threshold.",
        steps: [
          step("Detect", "No movement"),
          step("Contact", "Push and call fallback"),
          step("Decide", "Continue or reassign"),
          step("Complete", "Proof and settlement"),
        ],
        currentStep: 1,
        primary: "Open delivery action",
        primaryOutcome:
          "Delivery recovery opened with authorized location and handover proof.",
        tags: ["At risk", "Late", "Reroute"],
      }),
      adminCase({
        id: "customer-cancellation",
        kicker: "CUSTOMER CANCELLATION",
        title: "Cancellation requested after preparation",
        meta: "Restaurant order · terms accepted at 9:32",
        status: "Terms",
        tone: "warning",
        time: "14:05 left",
        facts: [
          fact("ORDER", "₹780"),
          fact("STAGE", "Prepared"),
          fact("FEE", "Partial"),
          fact("EVIDENCE", "Preparation confirmed"),
        ],
        detail:
          "Show the exact accepted cancellation terms and resolve the payable preparation amount before refund.",
        steps: [
          step("Terms", "Accepted version retrieved"),
          step("Stage", "Preparation confirmed"),
          step("Amount", "Fee calculated"),
          step("Result", "Refund and receipt"),
        ],
        currentStep: 2,
        primary: "Confirm calculated result",
        primaryOutcome:
          "Calculated cancellation result recorded for refund and receipt.",
        tags: ["At risk", "Refund"],
      }),
    ],
  },
  {
    screen: 151,
    navLabel: "Rides",
    path: "/admin/rides",
    title: "Ride and Captain Operations",
    subtitle: "Live safety, supply, trip exceptions and fare completion",
    role: "Mobility Controller",
    stats: [
      { label: "LIVE TRIPS", value: "2,418", note: "Bike, auto and cab" },
      { label: "SOS", value: "1", note: "Safety team active" },
      { label: "LOW SUPPLY", value: "3 zones", note: "No forced pricing" },
      { label: "COMPLETION", value: "98.8%", note: "Today" },
    ],
    filters: ["Safety", "Pickup delay", "No movement", "Fare", "Documents"],
    queueTitle: "Live ride exceptions",
    queueNote: "Safety, then continuity",
    note: "Location and contact data appear only to authorized responders for the active purpose.",
    items: [
      adminCase({
        id: "captain-sos",
        kicker: "SOS · RD-90218",
        title: "Captain safety alert",
        meta: "Jodhpur · customer and captain connected",
        status: "Critical",
        tone: "critical",
        time: "00:42",
        facts: [
          fact("TRIP", "RD-90218"),
          fact("VEHICLE", "Auto"),
          fact("CONTACT", "Connected"),
          fact("LOCATION", "Authorized"),
        ],
        detail:
          "Follow the incident protocol without exposing live location to unrelated teams.",
        steps: [
          step("Connect", "Both parties reached"),
          step("Assess", "Safety questions"),
          step("Assist", "Emergency action when needed"),
          step("Welfare check", "Close with reason"),
        ],
        currentStep: 1,
        primary: "Continue safety protocol",
        primaryOutcome:
          "The authorized safety team can continue the current protocol.",
        tags: ["Safety"],
        confirmation:
          "I am an authorized safety responder and will use location only for this incident.",
      }),
      adminCase({
        id: "pickup-delay",
        kicker: "PICKUP DELAY",
        title: "Captain is 11 minutes from pickup",
        meta: "Customer accepted a 6-minute arrival time",
        status: "Resolve",
        tone: "warning",
        time: "03:18 left",
        facts: [
          fact("TRIP", "RD-90244"),
          fact("ORIGINAL", "6 min"),
          fact("CURRENT", "11 min"),
          fact("BACKUP", "4 captains"),
        ],
        detail:
          "Offer a truthful revised arrival time or safe reassignment. Never silently replace the accepted captain.",
        steps: [
          step("Contact", "Captain response"),
          step("Compare", "Current arrival versus backup"),
          step("Customer choice", "Keep or reassign"),
          step("Reserve", "One captain only"),
        ],
        currentStep: 0,
        primary: "Start reassignment check",
        primaryOutcome:
          "A customer-visible arrival comparison is ready; no captain was silently replaced.",
        tags: ["Pickup delay", "No movement"],
      }),
      adminCase({
        id: "fare-review",
        kicker: "FARE REVIEW",
        title: "Toll amount differs from the trip path",
        meta: "Card authorization held · no debit yet",
        status: "Review",
        tone: "warning",
        time: "12:40 left",
        facts: [
          fact("FARE", "₹486"),
          fact("TOLL CLAIM", "₹75"),
          fact("PATH TOLL", "₹40"),
          fact("PAYMENT", "Held"),
        ],
        detail:
          "Verify the trip and receipt before asking the customer to approve the final card debit.",
        steps: [
          step("Trip path", "Permitted location evidence"),
          step("Toll", "Receipt and terms"),
          step("Fare", "Final calculation"),
          step("Approval", "Customer confirms"),
        ],
        currentStep: 1,
        primary: "Review fare evidence",
        primaryOutcome:
          "Fare evidence opened while the card debit remains held.",
        tags: ["Fare"],
      }),
    ],
  },
  {
    screen: 152,
    navLabel: "Work",
    path: "/admin/work",
    title: "Work and Campaign Governance",
    subtitle: "Funding, eligibility, terms, outcomes and fair payout",
    role: "Work Operations Controller",
    stats: [
      { label: "OPEN OUTPUTS", value: "12,840", note: "Funded capacity" },
      { label: "FUNDS HELD", value: "₹1.92Cr", note: "Reserved for outcomes" },
      { label: "PROOF REVIEW", value: "318", note: "Due today" },
      { label: "APPEALS", value: "24", note: "Independent review" },
    ],
    filters: ["Funding", "Eligibility", "Proof", "Payout", "Appeal"],
    queueTitle: "Governance queue",
    queueNote: "Funding and fairness",
    note: "No opportunity becomes public until funding, exact output, proof, review and payout terms are approved.",
    items: [
      adminCase({
        id: "retailer-campaign",
        kicker: "NEW CAMPAIGN · CP-2208",
        title: "Onboard 1,000 verified retailers",
        meta: "Manufacturer funded · Rajasthan · ₹450 approved outcome",
        status: "Approve terms",
        tone: "warning",
        time: "42 min",
        facts: [
          fact("FUNDING", "₹4.5L held"),
          fact("OUTPUT", "1,000"),
          fact("PAYOUT", "₹450"),
          fact("AREA", "Rajasthan"),
        ],
        detail:
          "Confirm bounded work, proportionate evidence, truthful potential and clear unsuccessful-output terms.",
        steps: [
          step("Funding", "Reserved"),
          step("Terms", "Output and proof"),
          step("Eligibility", "Profile and geography"),
          step("Publish", "Approved capacity"),
        ],
        currentStep: 1,
        primary: "Approve governed campaign",
        primaryOutcome:
          "Campaign terms approved for funded capacity; no earnings are guaranteed.",
        tags: ["Funding", "Eligibility"],
      }),
      adminCase({
        id: "proof-review",
        kicker: "PROOF REVIEW · WK-88201",
        title: "Retailer onboarding outcome submitted",
        meta: "GPS, KYC consent and activation match",
        status: "Review",
        tone: "neutral",
        time: "18 min",
        facts: [
          fact("WORK", "WK-88201"),
          fact("PAYOUT", "₹450"),
          fact("PROOF", "3 sources"),
          fact("CONFLICT", "None"),
        ],
        detail:
          "Evidence supports the outcome. The reviewer sees only information needed for this decision.",
        steps: [
          step("Integrity", "Metadata checked"),
          step("Outcome", "Activation confirmed"),
          step("Decision", "Approve or explain"),
          step("Payout", "Move to payable"),
        ],
        currentStep: 2,
        primary: "Approve outcome",
        secondary: "Request rework",
        primaryOutcome:
          "Outcome approved and moved to payable review.",
        secondaryOutcome:
          "One precise rework request was sent without changing eligibility.",
        tags: ["Proof", "Payout"],
      }),
      adminCase({
        id: "worker-appeal",
        kicker: "WORKER APPEAL · AP-1204",
        title: "Rejected catalogue proof disputed",
        meta: "Independent reviewer was not involved in the first decision",
        status: "Appeal",
        tone: "critical",
        time: "1 h left",
        facts: [
          fact("PAYOUT", "₹360"),
          fact("FIRST REASON", "Source mismatch"),
          fact("NEW EVIDENCE", "1 file"),
          fact("REVIEWER", "Independent"),
        ],
        detail:
          "The appeal shows the original policy, evidence and reason without silently damaging future eligibility.",
        steps: [
          step("Intake", "Appeal accepted"),
          step("Independence", "Reviewer assigned"),
          step("Recheck", "Policy and evidence"),
          step("Result", "Reason and payout"),
        ],
        currentStep: 2,
        primary: "Record appeal result",
        primaryOutcome:
          "Independent appeal result recorded with payout and eligibility effects.",
        tags: ["Appeal", "Proof", "Payout"],
        confirmation:
          "I was not involved in the first decision and reviewed the original reason and new evidence.",
      }),
    ],
  },
  {
    screen: 153,
    navLabel: "Trust & Safety",
    path: "/admin/content",
    title: "Social Trust and Safety",
    subtitle: "Content reports, rights, paid disclosure and proportionate action",
    role: "Trust and Safety Reviewer",
    stats: [
      { label: "REPORTS OPEN", value: "426", note: "Risk ranked" },
      { label: "HIGH HARM", value: "18", note: "Specialist queue" },
      { label: "AUTO LIMITED", value: "62", note: "Awaiting human review" },
      { label: "APPEALS DUE", value: "31", note: "Within target" },
    ],
    filters: ["High harm", "Rights", "Paid content", "Spam", "Appeals"],
    queueTitle: "Moderation queue",
    queueNote: "Harm and reach weighted",
    note: "Every action records policy, evidence, scope, duration, reason and appeal path.",
    items: [
      adminCase({
        id: "medical-claim",
        kicker: "HIGH HARM REPORT",
        title: "Short contains a dangerous medical claim",
        meta: "48K views · health specialist required",
        status: "Specialist",
        tone: "critical",
        time: "09:12 left",
        facts: [
          fact("FORMAT", "Short"),
          fact("REACH", "48K"),
          fact("REPORTS", "126"),
          fact("ACTION", "Distribution limited"),
        ],
        detail:
          "Limit reach while a qualified reviewer checks the claim. Preserve evidence without exposing reporter identity.",
        steps: [
          step("Contain", "Distribution limited"),
          step("Classify", "Policy and jurisdiction"),
          step("Specialist", "Health review"),
          step("Decide", "Restore, label or remove"),
        ],
        currentStep: 2,
        primary: "Open specialist review",
        primaryOutcome:
          "Qualified health review opened with reporter identity protected.",
        tags: ["High harm"],
        confirmation:
          "I am authorized to open this specialist review and will not expose reporter identity.",
      }),
      adminCase({
        id: "rights-match",
        kicker: "RIGHTS MATCH",
        title: "Long video matches registered content",
        meta: "Creator supplied ownership evidence and publication date",
        status: "Review",
        tone: "warning",
        time: "24 min",
        facts: [
          fact("MATCH", "92%"),
          fact("CLAIMANT", "Verified"),
          fact("CREATOR", "Verified"),
          fact("REVENUE", "Held"),
        ],
        detail:
          "Do not remove content or transfer revenue solely on an automated match. Both parties receive evidence and appeal access.",
        steps: [
          step("Match", "Fingerprint evidence"),
          step("Notice", "Creator response"),
          step("Rights review", "Documents and exceptions"),
          step("Result", "Content and revenue"),
        ],
        currentStep: 2,
        primary: "Record rights decision",
        primaryOutcome:
          "Rights decision recorded with evidence, revenue treatment and appeal access.",
        tags: ["Rights", "Appeals"],
      }),
      adminCase({
        id: "paid-disclosure",
        kicker: "PAID DISCLOSURE",
        title: "Campaign Short is missing clear disclosure",
        meta: "Funded campaign CP-2208 · 12K views",
        status: "Correct",
        tone: "warning",
        time: "37 min",
        facts: [
          fact("CAMPAIGN", "CP-2208"),
          fact("FORMAT", "Short"),
          fact("DISCLOSURE", "Missing"),
          fact("PAYOUT", "Held"),
        ],
        detail:
          "Ask the creator to correct disclosure before stronger action when safe. Campaign payout remains held.",
        steps: [
          step("Detect", "Campaign linkage"),
          step("Notify", "Correction request"),
          step("Recheck", "Disclosure visible"),
          step("Payout", "Release or explain"),
        ],
        currentStep: 1,
        primary: "Send correction request",
        primaryOutcome:
          "A precise disclosure correction was sent and payout remains held.",
        tags: ["Paid content"],
      }),
    ],
  },
  {
    screen: 154,
    navLabel: "Finance",
    path: "/admin/finance",
    title: "Finance and Reconciliation",
    subtitle: "Payments, holds, payouts, refunds and settlement integrity",
    role: "Finance Controller",
    stats: [
      { label: "TODAY FLOW", value: "₹2.8Cr", note: "Across payment methods" },
      { label: "MATCHED", value: "99.7%", note: "Money record to provider" },
      { label: "UNMATCHED", value: "82", note: "No money lost" },
      { label: "REFUNDS DUE", value: "₹4.2L", note: "Target protected" },
    ],
    filters: ["Unmatched", "Pending", "Refund", "Protected funds", "Payout"],
    queueTitle: "Finance exceptions",
    queueNote: "Money record first",
    note: "Balances are never overwritten. Corrections use balanced entries with independent approval.",
    items: [
      adminCase({
        id: "unmatched-payment",
        kicker: "UNMATCHED PAYMENT · PY-92018",
        title: "Payment provider success, platform pending",
        meta: "Customer payment ₹645 · order OR-84291",
        status: "Reconcile",
        tone: "critical",
        time: "05:11 left",
        facts: [
          fact("PAYMENT", "₹645"),
          fact("PROVIDER", "Success"),
          fact("MOOL STATUS", "Pending"),
          fact("DUPLICATE", "Blocked"),
        ],
        detail:
          "Match the signed payment event to the original intent before moving the order payment exactly once.",
        steps: [
          step("Authenticate", "Provider signature"),
          step("Match", "Intent and amount"),
          step("Post", "Balanced money entry"),
          step("Notify", "Order and customer"),
        ],
        currentStep: 1,
        primary: "Post verified result",
        primaryOutcome:
          "One balanced payment result is ready for independent approval.",
        tags: ["Unmatched", "Pending"],
        confirmation:
          "I verified the provider signature, payment intent, amount and duplicate protection.",
      }),
      adminCase({
        id: "advance-hold",
        kicker: "ADVANCE HOLD · PO-5821",
        title: "Supplier requests 30% advance release",
        meta: "Goods not delivered · buyer protection active",
        status: "Keep held",
        tone: "warning",
        time: "2 h",
        facts: [
          fact("ORDER", "₹1.42L"),
          fact("ADVANCE", "₹42,600"),
          fact("DELIVERY", "Pending"),
          fact("TERMS", "Hold until receipt"),
        ],
        detail:
          "The supplier sees secured funds, while settlement follows the accepted delivery and receipt terms.",
        steps: [
          step("Funds", "Secured"),
          step("Supplier notice", "Hold explained"),
          step("Goods receipt", "Buyer confirmation"),
          step("Settlement", "Release under terms"),
        ],
        currentStep: 2,
        primary: "Keep protection active",
        secondary: "Open accepted terms",
        primaryOutcome:
          "Advance remains protected until confirmed receipt.",
        secondaryOutcome:
          "The accepted delivery and release terms are open for review.",
        tags: ["Protected funds", "Pending"],
      }),
      adminCase({
        id: "refund-batch",
        kicker: "REFUND BATCH",
        title: "42 approved customer refunds ready",
        meta: "Source decisions and amounts verified",
        status: "Approve",
        tone: "warning",
        time: "31 min",
        facts: [
          fact("COUNT", "42"),
          fact("VALUE", "₹84,220"),
          fact("SOURCE", "Verified"),
          fact("PREPARED BY", "Finance Ops"),
        ],
        detail:
          "A separate approver checks total, funding source and duplicate protection before execution.",
        steps: [
          step("Decisions", "Approved cases"),
          step("Batch", "Amounts and payment methods"),
          step("Approver", "Independent check"),
          step("Execute", "Refund and receipt"),
        ],
        currentStep: 2,
        primary: "Approve refund batch",
        primaryOutcome:
          "Refund batch approved once for provider execution and receipts.",
        tags: ["Refund"],
        confirmation:
          "I did not prepare this batch and verified count, total, source and duplicate protection.",
      }),
    ],
  },
  {
    screen: 155,
    navLabel: "Support",
    path: "/admin/support",
    title: "Support, Disputes and Response Targets",
    subtitle: "One case timeline across customer, provider, worker and platform evidence",
    role: "Support Resolution Lead",
    stats: [
      { label: "OPEN CASES", value: "1,208", note: "All modules" },
      { label: "AT RISK", value: "42", note: "Escalated" },
      { label: "FIRST CONTACT", value: "3m 18s", note: "Median" },
      { label: "RESOLVED", value: "92%", note: "Without reopening" },
    ],
    filters: ["At risk", "Commerce", "Ride", "Work", "Payment", "Appeal"],
    queueTitle: "Resolution queue",
    queueNote: "Deadline and harm priority",
    note: "Users see the owner, current stage, next update, evidence used and reason for every result.",
    items: [
      adminCase({
        id: "damaged-grocery",
        kicker: "COMMERCE CASE · CS-8421",
        title: "Customer reports damaged grocery items",
        meta: "Photos, delivery proof and shop response available",
        status: "Decide",
        tone: "warning",
        time: "18:14 left",
        facts: [
          fact("ORDER", "OR-84291"),
          fact("CLAIM", "₹186"),
          fact("EVIDENCE", "Complete"),
          fact("SHOP", "Responded"),
        ],
        detail:
          "Review item-level evidence and accepted refund terms. Unrelated order history is not shown.",
        steps: [
          step("Intake", "Issue and amount"),
          step("Evidence", "Customer and fulfilment"),
          step("Response", "Shop statement"),
          step("Result", "Refund, replacement or reject"),
        ],
        currentStep: 3,
        primary: "Record reasoned result",
        primaryOutcome:
          "Item-level result recorded with the user-visible reason and next step.",
        tags: ["At risk", "Commerce"],
      }),
      adminCase({
        id: "ride-toll",
        kicker: "RIDE CASE · CS-8440",
        title: "Customer disputes final toll",
        meta: "Trip path, receipt and card hold available",
        status: "Review",
        tone: "warning",
        time: "32:02 left",
        facts: [
          fact("RIDE", "RD-90244"),
          fact("DISPUTE", "₹35"),
          fact("DEBIT", "Not taken"),
          fact("EVIDENCE", "Complete"),
        ],
        detail:
          "Resolve the toll before card approval. The customer never pays while the amount is under review.",
        steps: [
          step("Intake", "Disputed component"),
          step("Evidence", "Trip path and receipt"),
          step("Calculation", "Final fare"),
          step("Approval", "Customer sees result"),
        ],
        currentStep: 2,
        primary: "Confirm final fare",
        primaryOutcome:
          "Final fare is ready for customer review; no debit was taken.",
        tags: ["At risk", "Ride", "Payment"],
      }),
      adminCase({
        id: "work-appeal",
        kicker: "WORK APPEAL · CS-8459",
        title: "Worker challenges proof rejection",
        meta: "Independent reviewer assigned",
        status: "Appeal",
        tone: "critical",
        time: "44:50 left",
        facts: [
          fact("WORK", "WK-88201"),
          fact("PAYOUT", "₹450"),
          fact("POLICY", "v3.2"),
          fact("REVIEWER", "Independent"),
        ],
        detail:
          "The first reviewer cannot decide the appeal. Reputation impact stays paused until the appeal closes.",
        steps: [
          step("Appeal", "Accepted"),
          step("Evidence", "Original and new"),
          step("Independent review", "In progress"),
          step("Result", "Reason, payout and rating"),
        ],
        currentStep: 2,
        primary: "Open appeal review",
        primaryOutcome:
          "Independent appeal review opened with reputation impact paused.",
        tags: ["At risk", "Work", "Appeal"],
      }),
    ],
  },
  {
    screen: 156,
    navLabel: "Launch",
    path: "/admin/configuration",
    title: "Offering Provisioning and Launch",
    subtitle: "Create profile-specific products, services, outcomes and work, then release them safely",
    role: "Product Provisioning Controller",
    stats: [
      { label: "ACTIVE OFFERINGS", value: "18", note: "Products, services and outcomes" },
      { label: "PROFILE TARGETS", value: "29", note: "Personal plus 28 workspaces" },
      { label: "CANARY HEALTH", value: "99.2%", note: "Journey completion" },
      { label: "HELD BY TERMS", value: "7", note: "Funding, capacity or policy" },
    ],
    filters: ["Offerings", "Drafts", "Approval", "Canary", "Live", "Stopped"],
    queueTitle: "Products, services and launch control",
    queueNote: "Configure, approve, validate, then expand",
    note: "Eligible recipients are resolved when used. Administrators cannot export raw audience lists.",
    composer: true,
    items: [
      adminCase({
        id: "basket-growth",
        kicker: "WORKSPACE OFFERING · OFR-20260718-301",
        title: "Neighbourhood Basket Growth",
        meta: "Grocery / Kirana · Jodhpur · outcome contract",
        status: "Canary",
        tone: "warning",
        time: "5% live",
        facts: [
          fact("TARGET", "Grocery / Kirana"),
          fact("OUTCOME", "100 retained"),
          fact("MAX EXPOSURE", "₹50,000"),
          fact("HEALTH", "99.2%"),
        ],
        detail:
          "Eligible shops see one decision-ready card that opens exact outcome, readiness and maximum payable terms.",
        steps: [
          step("Foundation", "Registered capabilities"),
          step("Eligibility", "Profile and readiness"),
          step("Commercial", "Outcome, cap and make-good"),
          step("Experience", "Card and owner screen"),
          step("Approval", "Product, Finance and Operations"),
          step("Release", "5% canary then expand"),
        ],
        currentStep: 5,
        primary: "Review rollout",
        secondary: "Pause offering",
        primaryOutcome:
          "Canary health and user completion are ready for an expansion decision.",
        secondaryOutcome:
          "New eligibility paused while existing funded obligations stay protected.",
        tags: ["Offerings", "Canary", "Live"],
      }),
      adminCase({
        id: "stock-assistant",
        kicker: "FEATURE LAUNCH · FL-1042",
        title: "Retailer AI stock assistant",
        meta: "Verified retailers · Rajasthan · Hindi and English",
        status: "Approval",
        tone: "warning",
        time: "Tomorrow 10:00",
        facts: [
          fact("ELIGIBLE", "18,420"),
          fact("CHANNELS", "In-app + Push"),
          fact("FREQUENCY", "1 in 7 days"),
          fact("APP VERSION", "6.4+"),
        ],
        detail:
          "Launch only to verified retailer owners with compatible app versions. The action opens inside their workspace.",
        steps: [
          step("Purpose", "Feature and measurable outcome"),
          step("Audience", "Eligibility, area and consent"),
          step("Content", "Localized message and next action"),
          step("Checks", "Policy, frequency and conflicts"),
          step("Approval", "Independent check"),
          step("Publish", "Canary then eligible audience"),
        ],
        currentStep: 4,
        primary: "Approve canary launch",
        secondary: "Return to owner",
        primaryOutcome:
          "Pilot-audience delivery approved; full release stays held for health checks.",
        secondaryOutcome:
          "Launch returned to its owner with the required correction.",
        tags: ["Approval", "Canary"],
      }),
      adminCase({
        id: "captain-work",
        kicker: "FUNDED WORK · WK-LAUNCH-88",
        title: "Onboard 1,000 verified taxi captains",
        meta: "Jodhpur and Jaipur · funding secured · eligible workers",
        status: "Draft",
        tone: "neutral",
        time: "Ends 25 Jul",
        facts: [
          fact("CAPACITY", "1,000"),
          fact("FUNDING", "₹6L held"),
          fact("PAYOUT", "₹600 approved"),
          fact("AUDIENCE", "12,840 eligible"),
        ],
        detail:
          "Show the opportunity only to eligible verified work profiles. It opens exact terms and never auto-applies anyone.",
        steps: [
          step("Purpose", "Funded work output"),
          step("Audience", "Profile and area eligibility"),
          step("Content", "Terms and next action"),
          step("Checks", "Funding and frequency"),
          step("Approval", "Work Operations"),
          step("Publish", "Inbox and permitted push"),
        ],
        currentStep: 3,
        primary: "Send for Work approval",
        primaryOutcome:
          "Funded work sent for Work Operations approval; no worker was auto-applied.",
        tags: ["Drafts", "Approval"],
      }),
      adminCase({
        id: "basket-price-lock",
        kicker: "CONSUMER OFFER · OF-2091",
        title: "Nearby grocery basket price-lock",
        meta: "Selected pin codes · final price and fulfilment ready",
        status: "Scheduled",
        tone: "neutral",
        time: "Today 18:00",
        facts: [
          fact("REACH", "82,400"),
          fact("PIN CODES", "24"),
          fact("BUDGET", "₹2.4L"),
          fact("STOP", "Budget or complaints"),
        ],
        detail:
          "Customers receive the offer only where stock, price, fulfilment, refund and next action are live.",
        steps: [
          step("Offer", "Decision-ready supply"),
          step("Audience", "Area and consent"),
          step("Content", "Price and fulfilment"),
          step("Checks", "Stock, budget and frequency"),
          step("Approval", "Campaign owner"),
          step("Publish", "Scheduled with stop conditions"),
        ],
        currentStep: 5,
        primary: "Review scheduled launch",
        secondary: "Pause schedule",
        primaryOutcome:
          "Scheduled launch is ready with live supply and stop conditions.",
        secondaryOutcome:
          "Schedule paused before any new customer receives the offer.",
        tags: ["Offerings", "Approval"],
      }),
      adminCase({
        id: "pharmacy-renewal",
        kicker: "REQUIRED NOTICE · RN-662",
        title: "Pharmacy licence renewal action",
        meta: "42 pharmacy owners · required workspace action",
        status: "Ready",
        tone: "neutral",
        time: "Send now",
        facts: [
          fact("RECIPIENTS", "42"),
          fact("PURPOSE", "Compliance"),
          fact("CHANNELS", "Inbox + Chat + Email"),
          fact("EXPIRY", "30 days"),
        ],
        detail:
          "This required notice explains why it was received and opens the exact renewal action. It contains no promotion.",
        steps: [
          step("Trigger", "Verified expiry"),
          step("Audience", "Affected owners only"),
          step("Content", "Action and reason"),
          step("Checks", "No promotion"),
          step("Approval", "Compliance owner"),
          step("Publish", "Inbox and approved fallbacks"),
        ],
        currentStep: 4,
        primary: "Publish required notice",
        primaryOutcome:
          "Required notice published to 42 affected owners with no promotion.",
        tags: ["Approval", "Live"],
      }),
    ],
  },
  {
    screen: 163,
    navLabel: "Product Health",
    path: "/admin?view=activity-health",
    title: "User Activity and Product Health",
    subtitle: "Trace meaningful actions from product area to outcome without collecting private content",
    role: "Product Reliability Lead",
    stats: [
      { label: "JOURNEY SUCCESS", value: "99.18%", note: "Last 60 minutes" },
      { label: "AFFECTED USERS", value: "218", note: "Three owned incidents" },
      { label: "UNCAUGHT CRASHES", value: "7", note: "Down 42% after canary" },
      { label: "DATA FRESHNESS", value: "22 sec", note: "Events and traces healthy" },
    ],
    filters: ["Overview", "Journey failures", "User timeline", "APIs", "Releases", "Workspaces"],
    queueTitle: "Product health signals",
    queueNote: "Impact, then trace",
    note: "Private messages, payment credentials, clinical content and raw identifiers never enter this activity view.",
    items: [
      adminCase({
        id: "upi-return",
        kicker: "BUY JOURNEY · ANDROID 6.4.1",
        title: "Checkout confirmation failing after UPI return",
        meta: "184 users · payment confirmation · started 09:18",
        status: "Investigating",
        tone: "critical",
        time: "08:14 left",
        facts: [
          fact("SUCCESS", "91.2%"),
          fact("AFFECTED", "184"),
          fact("ACTION", "payment.confirm"),
          fact("TRACE", "TR-84F2"),
        ],
        detail:
          "The app shows pending correctly and blocks duplicates. Failures correlate with Android 6.4.1 and one payment connector release.",
        steps: [
          step("Detect", "Journey threshold crossed"),
          step("Correlate", "Release, device and payment trace"),
          step("Contain", "Canary rollback and duplicate guard"),
          step("Verify", "Synthetic and affected-user recovery"),
        ],
        currentStep: 2,
        primary: "Open technical trace",
        secondary: "Assign owner",
        primaryOutcome:
          "Trace TR-84F2 opened with client, payment and release correlation.",
        secondaryOutcome:
          "Reliability owner assigned with the current impact and response target.",
        tags: ["Overview", "Journey failures", "APIs", "Releases"],
      }),
      adminCase({
        id: "masked-user",
        kicker: "AUTHORIZED TIMELINE · CASE SU-771",
        title: "User U-83A… cannot finish stock import",
        meta: "Support purpose recorded · identity masked · access expires in 26 min",
        status: "Authorized",
        tone: "warning",
        time: "Live",
        facts: [
          fact("USER", "U-83A…"),
          fact("WORKSPACE", "Retailer"),
          fact("LAST AREA", "Stock import"),
          fact("ERROR", "CSV_ROW_42"),
        ],
        detail:
          "The timeline includes product area, action, outcome, latency and trace IDs. It excludes file contents, chats, passwords, OTPs and payment data.",
        steps: [
          step("Open", "Stock catalogue"),
          step("Action", "Import stock file"),
          step("Validate", "41 rows passed; row 42 failed"),
          step("Resolve", "Show exact correction and safe retry"),
        ],
        currentStep: 2,
        primary: "Open masked timeline",
        secondary: "End access",
        primaryOutcome:
          "Purpose-recorded masked timeline opened; access is logged.",
        secondaryOutcome:
          "Temporary user-timeline access ended immediately.",
        tags: ["User timeline", "Workspaces"],
        confirmation:
          "I have an active support purpose and will use only masked action outcomes.",
      }),
      adminCase({
        id: "proof-upload",
        kicker: "MANUFACTURER ONBOARDING",
        title: "Proof upload completion fell in Rajasthan",
        meta: "86 sessions · onboarding proof · Android low-memory devices",
        status: "At risk",
        tone: "warning",
        time: "Today",
        facts: [
          fact("COMPLETION", "72.4%"),
          fact("DROP", "+8.6%"),
          fact("DEVICE", "Low memory"),
          fact("ACTION", "proof.upload"),
        ],
        detail:
          "Files above 8 MB time out before resumable transfer. Document content is not copied into analytics.",
        steps: [
          step("Detect", "Completion anomaly"),
          step("Reproduce", "Synthetic low-memory device"),
          step("Fix", "Resize preview and resumable upload"),
          step("Verify", "Completion returns to baseline"),
        ],
        currentStep: 1,
        primary: "Open journey analysis",
        primaryOutcome:
          "Journey analysis opened with device and transfer correlation only.",
        tags: ["Journey failures", "Workspaces"],
      }),
      adminCase({
        id: "creator-canary",
        kicker: "RELEASE HEALTH · WEB 6.4.2",
        title: "Creator upload canary is healthy",
        meta: "5% traffic · 3,842 sessions · no regression",
        status: "Healthy",
        tone: "success",
        time: "38 min",
        facts: [
          fact("UPLOAD SUCCESS", "99.7%"),
          fact("P95 TIME", "1.8 sec"),
          fact("CRASH", "0"),
          fact("CANARY", "5%"),
        ],
        detail:
          "Upload outcomes are stable. Rights and content remain inside the creator service, not product analytics.",
        steps: [
          step("Baseline", "Previous release comparison"),
          step("Canary", "5% eligible traffic"),
          step("Observe", "Errors, time and completion"),
          step("Expand", "25% after owner approval"),
        ],
        currentStep: 2,
        primary: "Review canary expansion",
        secondary: "Hold release",
        primaryOutcome:
          "Canary evidence is ready for a separate expansion approval.",
        secondaryOutcome:
          "Release held at 5% without affecting active creator sessions.",
        tags: ["Overview", "Releases"],
      }),
      adminCase({
        id: "action-coverage",
        kicker: "ACTION COVERAGE",
        title: "All launch controls have stable action IDs",
        meta: "1,842 controls · 149 routes · contract tests passed",
        status: "Complete",
        tone: "success",
        time: "Build 1554330",
        facts: [
          fact("CONTROLS", "1,842"),
          fact("REGISTERED", "100%"),
          fact("FORBIDDEN FIELDS", "0"),
          fact("ROUTES", "149"),
        ],
        detail:
          "Android, iOS and web map controls to one governed action catalogue. Missing IDs or forbidden fields fail the build.",
        steps: [
          step("Declare", "Owner and purpose"),
          step("Validate", "Required and forbidden fields"),
          step("Trace", "User action to responsible service"),
          step("Release", "Synthetic journey gate"),
        ],
        currentStep: 3,
        primary: "Open action coverage",
        primaryOutcome:
          "Action coverage opened with build-gate evidence.",
        tags: ["Overview", "APIs", "Releases"],
      }),
    ],
  },
  {
    screen: 164,
    navLabel: "Signals & Consent",
    path: "/admin/configuration?view=telemetry-governance",
    title: "Signals, Consent and Personalization",
    subtitle: "Explainable intent, user controls and governed targeting",
    role: "Data Governance Controller",
    stats: [
      { label: "GOVERNED ACTION TYPES", value: "42", note: "Approved for launch" },
      { label: "CONSENT ELIGIBLE", value: "78.6%", note: "Personalization purpose" },
      { label: "SUPPRESSED", value: "14.2K", note: "Withdrawal, frequency or risk" },
      { label: "KILL SWITCHES", value: "0", note: "All classes healthy" },
    ],
    filters: ["Intent signals", "Segments", "Consent", "Event rules", "Retention", "Kill switches"],
    queueTitle: "Data and relevance controls",
    queueNote: "Purpose, then permission",
    note: "Administrators see estimates and inclusion reasons, never downloadable raw user lists.",
    items: [
      adminCase({
        id: "grocery-planning",
        kicker: "INTENT SEGMENT · SG-219",
        title: "Weekly grocery planning",
        meta: "Structured buy actions · 14 days · promotional consent required",
        status: "Ready",
        tone: "neutral",
        time: "82,140 eligible",
        facts: [
          fact("PURPOSE", "Relevant offer"),
          fact("ELIGIBLE", "82,140"),
          fact("SUPPRESSED", "11,286"),
          fact("EXPIRES", "14 days"),
        ],
        detail:
          "Includes deliberate basket, delivery and saved-staple actions. Excludes private text, clinical data and sensitive traits.",
        steps: [
          step("Purpose", "Grocery value and fulfilment"),
          step("Signal", "Allowed structured actions only"),
          step("Consent", "Eligible when used"),
          step("Explain", "Every inclusion has a reason"),
          step("Launch", "Send to Offering Provisioning"),
        ],
        currentStep: 3,
        primary: "Create launch draft",
        secondary: "Edit segment",
        primaryOutcome:
          "Audience rule sent to Offering Provisioning; message and approvals remain required.",
        secondaryOutcome:
          "Segment opened for a versioned rule change; no audience was exported.",
        tags: ["Intent signals", "Segments", "Consent"],
      }),
      adminCase({
        id: "captain-match",
        kicker: "WORK INTENT · SG-288",
        title: "Captain onboarding opportunity match",
        meta: "Verified workers · Jodhpur and Jaipur · funding active",
        status: "Live",
        tone: "success",
        time: "12,840 eligible",
        facts: [
          fact("PURPOSE", "Funded work"),
          fact("PROFILE", "Freelancer"),
          fact("CAPACITY", "1,000"),
          fact("PAYOUT", "₹600"),
        ],
        detail:
          "Eligibility uses verified work profile, area and declared preferences. It never auto-applies or guarantees earnings.",
        steps: [
          step("Verify", "Profile and area"),
          step("Match", "Funded capacity"),
          step("Explain", "Why it is shown"),
          step("Act", "User reviews terms and applies"),
        ],
        currentStep: 2,
        primary: "Review matched audience",
        primaryOutcome:
          "Aggregate matched audience opened with eligibility reasons and no raw identities.",
        tags: ["Intent signals", "Segments"],
      }),
      adminCase({
        id: "consent-withdrawal",
        kicker: "CONSENT SUPPRESSION · CS-41",
        title: "Personalization withdrawal enforced",
        meta: "1,284 accounts · completed in 18 seconds",
        status: "Complete",
        tone: "success",
        time: "Today",
        facts: [
          fact("WITHDRAWALS", "1,284"),
          fact("NEW TARGETING", "Stopped"),
          fact("REQUIRED EVENTS", "Purpose-separated"),
          fact("TIME", "18 sec"),
        ],
        detail:
          "Promotional eligibility stopped immediately. Transactional, safety and legally required processing stays separate.",
        steps: [
          step("Receive", "Consent change"),
          step("Suppress", "Remove from eligible audiences"),
          step("Propagate", "Invalidate active audience cache"),
          step("Confirm", "Preference and audit updated"),
        ],
        currentStep: 3,
        primary: "View suppression proof",
        primaryOutcome:
          "Aggregate suppression proof opened without exposing account identities.",
        tags: ["Consent", "Retention"],
      }),
      adminCase({
        id: "action-event",
        kicker: "ACTION DATA POLICY",
        title: "Privacy-safe action monitoring",
        meta: "All supported actions · controlled validation · transaction safeguards",
        status: "Approved",
        tone: "success",
        time: "Updated 2 h",
        facts: [
          fact("OWNER", "Product Platform"),
          fact("RETENTION", "90 days raw"),
          fact("MASKING", "Required"),
          fact("FREE TEXT", "Blocked"),
        ],
        detail:
          "Records the action, product area, result, time and audit reference. Form values, messages, files and touch coordinates are rejected.",
        steps: [
          step("Declare", "Purpose and owner"),
          step("Scan", "Forbidden fields"),
          step("Approve", "Privacy and security"),
          step("Monitor", "Volume, quality and misuse"),
        ],
        currentStep: 3,
        primary: "Open event policy",
        secondary: "Pause event class",
        primaryOutcome:
          "Approved action-data policy and forbidden-field controls opened.",
        secondaryOutcome:
          "New action-event collection paused without blocking product journeys.",
        tags: ["Event rules", "Retention"],
      }),
      adminCase({
        id: "kill-switches",
        kicker: "EMERGENCY CONTROL",
        title: "Personalization and telemetry kill switches",
        meta: "Independent by class, app version, geography and workspace",
        status: "Ready",
        tone: "warning",
        time: "Tested weekly",
        facts: [
          fact("PERSONALIZATION", "On"),
          fact("PRODUCT HEALTH", "On"),
          fact("SESSION REPLAY", "Off"),
          fact("LAST VALIDATION", "12 Jul"),
        ],
        detail:
          "Stop one event or targeting class without blocking orders, payments, rides, social or workspace operations.",
        steps: [
          step("Choose", "Exact class and scope"),
          step("Preview", "Affected health and audiences"),
          step("Approve", "Authorized controller"),
          step("Stop", "Immediate configuration"),
          step("Recover", "Versioned re-enable after validation"),
        ],
        currentStep: 0,
        primary: "Open kill switches",
        secondary: "Run controlled validation",
        primaryOutcome:
          "Scoped kill-switch controls opened; no class was stopped yet.",
        secondaryOutcome:
          "Validation completed without sending data or blocking user actions.",
        tags: ["Kill switches", "Event rules"],
        confirmation:
          "I reviewed the exact class and scope and confirmed core journeys remain available.",
      }),
    ],
  },
];

export const defaultAdminScreen = adminScreens[0];

export function getAdminScreen(
  pathname: string,
  view?: string,
): AdminScreen {
  if (view === "activity-health") {
    return adminScreens.find((screen) => screen.screen === 163) ?? defaultAdminScreen;
  }
  if (view === "telemetry-governance") {
    return adminScreens.find((screen) => screen.screen === 164) ?? defaultAdminScreen;
  }
  return (
    adminScreens.find(
      (screen) => screen.path.split("?")[0] === pathname && !screen.path.includes("?"),
    ) ?? defaultAdminScreen
  );
}

export const adminProfileTargets = [
  "Personal user",
  "FMCG Manufacturer",
  "FMCG Supplier / Distributor",
  "Raw Material Supplier",
  "Packaging Supplier",
  "Grocery / Kirana Shop",
  "General Retail Shop / Dukaan",
  "Individual Product Seller",
  "Restaurant / Dhaba / Cafe",
  "Cloud Kitchen",
  "Tiffin Provider",
  "Individual Doctor",
  "Clinic",
  "Hospital",
  "Medical Store / Pharmacy",
  "Salon / Parlour",
  "Home Beauty Provider",
  "Individual Service Provider",
  "Bike Captain",
  "Auto Captain",
  "Cab / Car Captain",
  "Delivery Partner",
  "Local Porter / Goods Transporter",
  "Transport / Fleet Operator",
  "Shorts Creator",
  "Long-Form Video Creator",
  "Multi-Format Creator",
  "Freelancer / Field Partner",
  "Get It Done Provider",
] as const;
